apiVersion: skaffold/v3
kind: Config
metadata:
  name: verification-service
build:
  artifacts:
    - image: verification-service
      context: .
      sync:
        infer:
          - cmd/**/*
          - internal/**/*
      docker:
        dockerfile: build/api/Dockerfile
    - image: verification-service-postgres-migrate
      context: .
      sync:
        infer:
          - migrations/*
      docker:
        dockerfile: build/migrate/Dockerfile
  tagPolicy:
    sha256: {}
deploy:
  helm:
    releases:
    - name: verification-service
      chartPath: deployments/minikube/helm
      valuesFiles:
        - deployments/minikube/helm/values.yaml
      setValues:
        skaffold: "true"
