apiVersion: v1
kind: Service
metadata:
  name: {{ include "verification-service.fullname" . }}
  labels:
    {{- include "verification-service.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.application.port }}
      targetPort: 80
      protocol: TCP
  selector:
    {{- include "verification-service.selectorLabels" . | nindent 4 }}
