apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "verification-service.fullname" . }}-postgres
spec:
  serviceName: {{ include "verification-service.fullname" . }}-postgres
  selector:
    matchLabels:
      {{- include "verification-service.selectorLabelsPostgres" . | nindent 6 }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "verification-service.selectorLabelsPostgres" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          imagePullPolicy: {{ .Values.postgres.imagePullPolicy }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password }}
          args:
            - postgres
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: {{ .Values.postgres.port }}
              hostPort: {{ .Values.postgres.port }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: "{{ .Chart.Name }}-postgres-data"
      volumes:
        - name: "{{ .Chart.Name }}-postgres-data"
          persistentVolumeClaim:
            claimName: {{ include "verification-service.fullname" . }}-postgres-persistent-volume-claim
