apiVersion: v1
kind: Service
metadata:
  name: {{ include "verification-service.fullname" . }}-postgres
  labels:
    {{- include "verification-service.labelsPostgres" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
  selector:
    {{- include "verification-service.selectorLabelsPostgres" . | nindent 4 }}
