kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "verification-service.fullname" . }}-postgres-persistent-volume-claim
  labels:
    {{- include "verification-service.labelsPostgres" . | nindent 4 }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
